# Generated by Django 6.0.5 on 2026-06-17 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModalityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("modality", "Modality"), ("points", "Points")],
                        max_length=20,
                    ),
                ),
                (
                    "tournament_competitor_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modality_types",
                        to="seasons.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Escalao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("min_participants", models.IntegerField(blank=True, null=True)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("points", models.JSONField(default=list)),
                (
                    "modality_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escaloes",
                        to="modality_types.modalitytype",
                    ),
                ),
            ],
        ),
    ]
