"""init

Revision ID: 96bbb696369b
Revises:
Create Date: 2025-12-01 16:54:37.824893

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96bbb696369b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_ranking",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("goals_for", sa.Integer(), nullable=False),
        sa.Column("goals_against", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_team_ranking_team_id"),
        "team_ranking",
        ["team_id"],
        unique=False,
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_team_ranking_tournament_id"),
        "team_ranking",
        ["tournament_id"],
        unique=False,
        schema="ranking",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ranking_team_ranking_tournament_id"),
        table_name="team_ranking",
        schema="ranking",
    )
    op.drop_index(
        op.f("ix_ranking_team_ranking_team_id"),
        table_name="team_ranking",
        schema="ranking",
    )
    op.drop_table("team_ranking", schema="ranking")
    # ### end Alembic commands ###
