"""update models

Revision ID: bd9b89d77878
Revises: 96bbb696369b
Create Date: 2025-12-06 18:03:07.411798

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd9b89d77878"
down_revision: Union[str, Sequence[str], None] = "96bbb696369b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_ranking",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("total_points", sa.Float(), nullable=False),
        sa.Column("modality_breakdown", sa.JSON(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_course_ranking_course_id"),
        "course_ranking",
        ["course_id"],
        unique=False,
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_course_ranking_season_id"),
        "course_ranking",
        ["season_id"],
        unique=False,
        schema="ranking",
    )
    op.create_table(
        "general_ranking",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Float(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_general_ranking_course_id"),
        "general_ranking",
        ["course_id"],
        unique=False,
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_general_ranking_season_id"),
        "general_ranking",
        ["season_id"],
        unique=False,
        schema="ranking",
    )
    op.create_table(
        "modality_ranking",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("modality_id", sa.UUID(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_modality_ranking_course_id"),
        "modality_ranking",
        ["course_id"],
        unique=False,
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_modality_ranking_modality_id"),
        "modality_ranking",
        ["modality_id"],
        unique=False,
        schema="ranking",
    )
    op.create_index(
        op.f("ix_ranking_modality_ranking_season_id"),
        "modality_ranking",
        ["season_id"],
        unique=False,
        schema="ranking",
    )
    op.drop_table("team_ranking", schema="ranking")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_ranking",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tournament_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("team_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("wins", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("draws", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("losses", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("goals_for", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("goals_against", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("points", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="team_ranking_pkey"),
        schema="ranking",
    )
    op.drop_index(
        op.f("ix_ranking_modality_ranking_season_id"),
        table_name="modality_ranking",
        schema="ranking",
    )
    op.drop_index(
        op.f("ix_ranking_modality_ranking_modality_id"),
        table_name="modality_ranking",
        schema="ranking",
    )
    op.drop_index(
        op.f("ix_ranking_modality_ranking_course_id"),
        table_name="modality_ranking",
        schema="ranking",
    )
    op.drop_table("modality_ranking", schema="ranking")
    op.drop_index(
        op.f("ix_ranking_general_ranking_season_id"),
        table_name="general_ranking",
        schema="ranking",
    )
    op.drop_index(
        op.f("ix_ranking_general_ranking_course_id"),
        table_name="general_ranking",
        schema="ranking",
    )
    op.drop_table("general_ranking", schema="ranking")
    op.drop_index(
        op.f("ix_ranking_course_ranking_season_id"),
        table_name="course_ranking",
        schema="ranking",
    )
    op.drop_index(
        op.f("ix_ranking_course_ranking_course_id"),
        table_name="course_ranking",
        schema="ranking",
    )
    op.drop_table("course_ranking", schema="ranking")
    # ### end Alembic commands ###
