from apps.nucleus.models import Nucleus
from django.db import models


class AdminRole(models.TextChoices):
    GENERAL_ADMIN = "general_admin", "General Admin"
    NUCLEO_ADMIN = "nucleo_admin", "Nucleo Admin"


class Admin(models.Model):
    id = models.UUIDField(primary_key=True, editable=False)  # generated by keycloak

    username = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    role = models.CharField(max_length=255, choices=AdminRole.choices)
    active = models.BooleanField(default=True)

    nucleos = models.ManyToManyField(Nucleus, related_name="admins", blank=True)

    @property
    def courses(self) -> list:
        """Return a list of courses associated with the admin's nucleos."""
        if self.role != AdminRole.NUCLEO_ADMIN:
            return None

        return list(
            set(
                course
                for nucleo in self.nucleos.all()
                for course in nucleo.courses.all()
            )
        )

    def __str__(self):
        return self.name
