"""make regulations independent

Revision ID: 1217187ea5c2
Revises: 63a521b349d0
Create Date: 2026-02-25 14:12:24.651639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1217187ea5c2'
down_revision: Union[str, Sequence[str], None] = '63a521b349d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('regulation_modality_id_fkey', 'regulation', schema='modalities', type_='foreignkey')
    op.drop_column('regulation', 'modality_id', schema='modalities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regulation', sa.Column('modality_id', sa.UUID(), autoincrement=False, nullable=True), schema='modalities')
    op.create_foreign_key('regulation_modality_id_fkey', 'regulation', 'modality', ['modality_id'], ['id'], source_schema='modalities', referent_schema='modalities')
    # ### end Alembic commands ###
