"""init

Revision ID: 1b21539d9870
Revises:
Create Date: 2025-12-06 16:24:42.624238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b21539d9870"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modality",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("COLETIVA", "INDIVIDUAL", "MISTA", name="modalitytype"),
            nullable=False,
        ),
        sa.Column("scoring_schema", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="modalities",
    )
    op.create_table(
        "student",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("student_number", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("is_member", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("student_number"),
        schema="modalities",
    )
    op.create_index(
        op.f("ix_modalities_student_course_id"),
        "student",
        ["course_id"],
        unique=False,
        schema="modalities",
    )
    op.create_table(
        "team",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("modality_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("players", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="modalities",
    )
    op.create_index(
        op.f("ix_modalities_team_course_id"),
        "team",
        ["course_id"],
        unique=False,
        schema="modalities",
    )
    op.create_index(
        op.f("ix_modalities_team_modality_id"),
        "team",
        ["modality_id"],
        unique=False,
        schema="modalities",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_modalities_team_modality_id"), table_name="team", schema="modalities"
    )
    op.drop_index(
        op.f("ix_modalities_team_course_id"), table_name="team", schema="modalities"
    )
    op.drop_table("team", schema="modalities")
    op.drop_index(
        op.f("ix_modalities_student_course_id"),
        table_name="student",
        schema="modalities",
    )
    op.drop_table("student", schema="modalities")
    op.drop_table("modality", schema="modalities")
    # ### end Alembic commands ###
