"""add logo_url to nucleo

Revision ID: a02ffb6e97cf
Revises: 007
Create Date: 2026-03-29 19:13:22.636523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02ffb6e97cf'
down_revision: Union[str, Sequence[str], None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_nucleo_id', table_name='course', schema='modalities')
    op.drop_index('ix_modality_modality_type_id', table_name='modality', schema='modalities')
    op.alter_column('modality_type', 'is_playoff',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'),
               schema='modalities')
    op.add_column('nucleo', sa.Column('logo_url', sa.Text(), nullable=True), schema='modalities')
    op.drop_index('ix_outbox_event_aggregate_id', table_name='outbox_event', schema='modalities')
    op.drop_index('ix_outbox_event_aggregate_type', table_name='outbox_event', schema='modalities')
    op.drop_index('ix_outbox_event_event_type', table_name='outbox_event', schema='modalities')
    op.drop_index('ix_outbox_event_published', table_name='outbox_event', schema='modalities')
    op.drop_index('ix_outbox_event_published_created', table_name='outbox_event', schema='modalities')
    op.create_index(op.f('ix_modalities_outbox_event_aggregate_id'), 'outbox_event', ['aggregate_id'], unique=False, schema='modalities')
    op.create_index(op.f('ix_modalities_outbox_event_aggregate_type'), 'outbox_event', ['aggregate_type'], unique=False, schema='modalities')
    op.create_index(op.f('ix_modalities_outbox_event_event_type'), 'outbox_event', ['event_type'], unique=False, schema='modalities')
    op.create_index(op.f('ix_modalities_outbox_event_published'), 'outbox_event', ['published'], unique=False, schema='modalities')
    op.drop_index('ix_student_course_id', table_name='student', schema='modalities')
    op.drop_index('ix_team_course_id', table_name='team', schema='modalities')
    op.drop_index('ix_team_modality_id', table_name='team', schema='modalities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_team_modality_id', 'team', ['modality_id'], unique=False, schema='modalities')
    op.create_index('ix_team_course_id', 'team', ['course_id'], unique=False, schema='modalities')
    op.create_index('ix_student_course_id', 'student', ['course_id'], unique=False, schema='modalities')
    op.drop_index(op.f('ix_modalities_outbox_event_published'), table_name='outbox_event', schema='modalities')
    op.drop_index(op.f('ix_modalities_outbox_event_event_type'), table_name='outbox_event', schema='modalities')
    op.drop_index(op.f('ix_modalities_outbox_event_aggregate_type'), table_name='outbox_event', schema='modalities')
    op.drop_index(op.f('ix_modalities_outbox_event_aggregate_id'), table_name='outbox_event', schema='modalities')
    op.create_index('ix_outbox_event_published_created', 'outbox_event', ['published', 'created_at'], unique=False, schema='modalities')
    op.create_index('ix_outbox_event_published', 'outbox_event', ['published'], unique=False, schema='modalities')
    op.create_index('ix_outbox_event_event_type', 'outbox_event', ['event_type'], unique=False, schema='modalities')
    op.create_index('ix_outbox_event_aggregate_type', 'outbox_event', ['aggregate_type'], unique=False, schema='modalities')
    op.create_index('ix_outbox_event_aggregate_id', 'outbox_event', ['aggregate_id'], unique=False, schema='modalities')
    op.drop_column('nucleo', 'logo_url', schema='modalities')
    op.alter_column('modality_type', 'is_playoff',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'),
               schema='modalities')
    op.create_index('ix_modality_modality_type_id', 'modality', ['modality_type_id'], unique=False, schema='modalities')
    op.create_index('ix_course_nucleo_id', 'course', ['nucleo_id'], unique=False, schema='modalities')
    # ### end Alembic commands ###
