"""init

Revision ID: c45dfb49b5e0
Revises:
Create Date: 2025-12-01 16:54:10.275884

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c45dfb49b5e0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modality",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="modalities",
    )
    op.create_table(
        "rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("modality_id", sa.UUID(), nullable=False),
        sa.Column("points_for_win", sa.Integer(), nullable=False),
        sa.Column("points_for_draw", sa.Integer(), nullable=False),
        sa.Column("points_for_loss", sa.Integer(), nullable=False),
        sa.Column(
            "scoring_formula", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["modality_id"],
            ["modalities.modality.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="modalities",
    )
    op.create_index(
        op.f("ix_modalities_rule_modality_id"),
        "rule",
        ["modality_id"],
        unique=False,
        schema="modalities",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_modalities_rule_modality_id"), table_name="rule", schema="modalities"
    )
    op.drop_table("rule", schema="modalities")
    op.drop_table("modality", schema="modalities")
    # ### end Alembic commands ###
