export * from './client';
export * from './teams';
export * from './students';
export * from './tournaments';
export * from './matches';
export * from './competitors';
export * from './ranking';
export * from './regulations';
export * from './nucleos';
