"""
Django settings for competition_api_v2 project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h(dq0b&v@(glrtzh%4704m%-=dex0u-gf6i@r%+cu$g1_2+e=("

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = [
    "*",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_prometheus",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "admin_api.middleware.StructlogMiddleware",  # Structured logging context
    "admin_api.middleware.KeycloakJWTMiddleware",  # JWT validation & user/role extraction
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_ROUTER_TRAILING_SLASH": False,
}
APPEND_SLASH = True

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Competition API (Admin API)",
    "DESCRIPTION": "API for managing TACA competitions - used by administrators",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/admin",
}


ROOT_URLCONF = "competition_api_v2.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "competition_api_v2.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Keycloak Admin API Configuration
# ---------------------------------------------------------------------------
KEYCLOAK_INTERNAL_URL = os.environ.get(
    "KEYCLOAK_INTERNAL_URL", "http://keycloak:8080/keycloak"
)
KEYCLOAK_REALM = os.environ.get("KEYCLOAK_REALM", "taca-ua")
KEYCLOAK_JWKS_URI = (
    f"{KEYCLOAK_INTERNAL_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs"
)
KEYCLOAK_ISSUER = os.environ.get(
    "KEYCLOAK_ISSUER",
    f"{KEYCLOAK_INTERNAL_URL}/realms/{KEYCLOAK_REALM}",  # fallback for local dev without nginx
)
KEYCLOAK_ADMIN_SERVER_URL = (
    os.environ.get("KEYCLOAK_ADMIN_SERVER_URL", KEYCLOAK_INTERNAL_URL).rstrip("/") + "/"
)
KEYCLOAK_ADMIN_USERNAME = os.environ.get("KEYCLOAK_ADMIN_USERNAME", "admin")
KEYCLOAK_ADMIN_PASSWORD = os.environ.get("KEYCLOAK_ADMIN_PASSWORD", "admin")
KEYCLOAK_ADMIN_REALM = os.environ.get("KEYCLOAK_ADMIN_REALM", KEYCLOAK_REALM)
KEYCLOAK_ADMIN_USER_REALM = os.environ.get("KEYCLOAK_ADMIN_USER_REALM", "master")
KEYCLOAK_ADMIN_VERIFY_SSL = (
    os.environ.get("KEYCLOAK_ADMIN_VERIFY_SSL", "true").lower() == "true"
)
KEYCLOAK_VALIDATE_ISSUER = (
    os.environ.get("DEV_MODE", "false").lower()
    == "false"  # In dev mode, skip issuer validation to allow flexibility with Keycloak URLs
)


# ---------------------------------------------------------------------------
# Development auth bypass (for local development without Keycloak)
# ---------------------------------------------------------------------------
DEV_AUTH_BYPASS_ENABLED = (
    os.environ.get("DEV_AUTH_BYPASS_ENABLED", "false").lower() == "true"
)
DEV_AUTH_BYPASS_ROLES = os.environ.get("DEV_AUTH_BYPASS_ROLES", "general_admin").split(
    ","
)
DEV_AUTH_BYPASS_TOKEN = os.environ.get("DEV_AUTH_BYPASS_TOKEN", "")
