"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from pythonjsonlogger import jsonlogger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-n1*yt*h^!p*&*btek$ns=*8h+2y+mk*&*owcjd=z2t4jlv3!$h"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "true").lower() == "true"

DOMAIN = os.getenv("DOMAIN", "localhost")

ALLOWED_HOSTS = [
    "competition-api-v3",
    "localhost",  # for health check
    DOMAIN,
]


# Application definition

INSTALLED_APPS = [
    "django_prometheus",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "drf_spectacular",
    "apps.admins",
    "apps.athletes",
    "apps.courses",
    "apps.matches",
    "apps.modalities",
    "apps.modality_types",
    "apps.nucleus",
    "apps.ranking",
    "apps.regulations",
    "apps.seasons",
    "apps.staff",
    "apps.teams",
    "apps.tournaments",
    "apps.projections",
    "apps.plataform_configs",
    "workers.projections_updater",
    "workers.ranking_updater",
    "workers.matches_state_updater",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "shared.auth.middleware.KeycloakJWTMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
    "shared.logging.middleware.RequestLoggingMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "taca_ua"),
        "USER": os.getenv("POSTGRES_USER", "user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "password"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# OpenAPI/Swagger settings

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Competition API",
    "DESCRIPTION": "API for managing Taca UA competition",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
    },
    "AUTHENTICATION_WHITELIST": [
        "rest_framework.authentication.SessionAuthentication",
        # "rest_framework.authentication.BasicAuthentication",
    ],
}


# Loki Logging settings

LOKI_LOGGING_URL = os.getenv(
    "LOKI_LOGGING_URL", "http://localhost:3100/loki/api/v1/push"
)
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "ignore_health_metrics": {
            "()": "config.logging_filters.IgnoreHealthMetricsFilter"
        },
        "ignore_health_metrics_access": {
            "()": "config.logging_filters.IgnoreHealthMetricsAccessFilter"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["ignore_health_metrics"],
        },
        "loki": {
            "class": "logging_loki.LokiHandler",
            "url": LOKI_LOGGING_URL,
            "tags": {
                "application": "django-api",
                "environment": "dev",
            },
            "version": "1",
            "formatter": "json",
            "filters": ["ignore_health_metrics", "ignore_health_metrics_access"],
        },
        "console_simple": {
            "class": "logging.StreamHandler",
            "filters": ["ignore_health_metrics", "ignore_health_metrics_access"],
        },
    },
    "formatters": {
        "json": {
            "()": jsonlogger.JsonFormatter,
            "fmt": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
        "verbose": {
            "format": "[%(asctime)s] [%(levelname)s] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "root": {
        "handlers": ["console", "loki"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["loki", "console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "uvicorn.access": {
            "handlers": ["loki", "console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["loki", "console_simple"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "gunicorn.access": {
            "handlers": ["loki", "console_simple"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "request_logger": {
            "handlers": ["loki"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}


# Minio settings
MINIO_SERVICE_URL = os.getenv("MINIO_SERVICE_URL", "localhost:9000")
MINIO_USER = os.getenv("MINIO_USER", "minioadmin")
MINIO_PASSWORD = os.getenv("MINIO_PASSWORD", "minioadmin")
MINIO_USE_SSL = os.getenv("MINIO_USE_SSL", "false").lower() == "true"


# Keycloak settings
KEYCLOAK_REALM = os.getenv("KEYCLOAK_REALM", "taca-ua")
KEYCLOAK_ADMIN_SERVER_URL = os.getenv(
    "KEYCLOAK_ADMIN_SERVER_URL", "http://localhost:8080/auth/"
)
KEYCLOAK_ADMIN_USERNAME = os.getenv("KEYCLOAK_ADMIN_USERNAME", "admin")
KEYCLOAK_ADMIN_PASSWORD = os.getenv("KEYCLOAK_ADMIN_PASSWORD", "admin")
KEYCLOAK_ADMIN_REALM = os.getenv("KEYCLOAK_ADMIN_REALM", KEYCLOAK_REALM)
KEYCLOAK_ADMIN_USER_REALM = os.getenv("KEYCLOAK_ADMIN_USER_REALM", "master")
KEYCLOAK_ADMIN_VERIFY_SSL = (
    os.getenv("KEYCLOAK_ADMIN_VERIFY_SSL", "false").lower() == "true"
)
KEYCLOAK_ISSUER_URL = os.getenv(
    "KEYCLOAK_ISSUER_URL", f"http://{DOMAIN}:8080/auth/realms/{KEYCLOAK_REALM}"
)
KEYCLOAK_VALIDATE_ISSUER = (
    os.getenv("KEYCLOAK_VALIDATE_ISSUER", "false").lower() == "true"
)
KEYCLOAK_JWKS_URI = (
    f"{KEYCLOAK_ADMIN_SERVER_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs"
)


# System settings
API_ENDPOINT_PREFIX = (
    os.getenv("API_ENDPOINT_PREFIX", "/api/v1").rstrip("/").lstrip("/")
)
DEFAULT_SEASON_NAME = os.getenv("DEFAULT_SEASON_NAME", "Default Season")
DEV_AUTH_BYPASS_ENABLED = (
    os.getenv("DEV_AUTH_BYPASS_ENABLED", "false").lower() == "true"
)
