# Generated by Django 6.0.5 on 2026-07-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="journey",
        ),
    ]
