# Generated by Django 6.0.5 on 2026-07-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_remove_match_journey"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MatchComment",
            new_name="MatchOccurrence",
        ),
        migrations.AlterField(
            model_name="matchoccurrence",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occurrences",
                to="matches.match",
            ),
        ),
    ]
