# Generated by Django 6.0.5 on 2026-06-17 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("athletes", "0001_initial"),
        ("modalities", "0001_initial"),
        ("modality_types", "0001_initial"),
        ("seasons", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "competitor_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("team", "Team")],
                        max_length=20,
                    ),
                ),
                (
                    "tournament_format",
                    models.CharField(
                        choices=[("free", "Free"), ("league", "League")],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modalities.modality",
                    ),
                ),
                (
                    "scoring_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="modality_types.modalitytype",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="seasons.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentCompetitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="athletes.athlete",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="tournaments.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "team", "athlete")},
            },
        ),
        migrations.CreateModel(
            name="LeagueSettings",
            fields=[
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="league_settings",
                        serialize=False,
                        to="tournaments.tournament",
                    ),
                ),
                ("win_points", models.PositiveIntegerField(default=3)),
                ("draw_points", models.PositiveIntegerField(default=1)),
                ("loss_points", models.PositiveIntegerField(default=0)),
                (
                    "draw_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("points_difference", "Points Difference"),
                            ("points_scored", "Points Scored"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeagueStanding",
            fields=[
                (
                    "competitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="tournaments.tournamentcompetitor",
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                ("played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("points_for", models.PositiveIntegerField(default=0)),
                ("points_against", models.PositiveIntegerField(default=0)),
                ("league_points", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TournamentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "competitor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="tournaments.tournamentcompetitor",
                    ),
                ),
            ],
        ),
    ]
