# Generated by Django 6.0.5 on 2026-06-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_position", models.PositiveIntegerField()),
                ("ending_position", models.PositiveIntegerField()),
                (
                    "tournament_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualification_sources",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "tournament_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualification_slots",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
    ]
