# Generated by Django 6.0.5 on 2026-06-27 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0002_qualificationslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualificationslot",
            name="tournament_target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualification_targets",
                to="tournaments.tournament",
            ),
        ),
    ]
