# Generated by Django 6.0.5 on 2026-07-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_remove_match_journey"),
        ("tournaments", "0003_alter_qualificationslot_tournament_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueMatch",
            fields=[
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="matches.match",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
            ],
        ),
    ]
