# Generated by Django 6.0.5 on 2026-07-06 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0002_remove_match_journey"),
        ("tournaments", "0004_leaguematch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaguematch",
            name="match",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="league_match",
                serialize=False,
                to="matches.match",
            ),
        ),
    ]
