# Generated by Django 6.0.5 on 2026-07-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournaments", "0005_alter_leaguematch_match"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaguesettings",
            name="draw_rule",
        ),
    ]
