# Generated by Django 6.0.5 on 2026-06-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectionUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projection_type",
                    models.CharField(
                        choices=[
                            ("team", "Team"),
                            ("athlete", "Athlete"),
                            ("tournament", "Tournament"),
                            ("match", "Match"),
                            ("tournament_standing", "Tournament Standing"),
                            ("general_ranking", "General Ranking"),
                            ("modality_ranking", "Modality Ranking"),
                            ("nucleo", "Nucleo"),
                            ("season", "Season"),
                            ("regulation", "Regulation"),
                        ],
                        max_length=255,
                    ),
                ),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
            ],
        ),
    ]
