# Generated by Django 6.0.5 on 2026-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections_updater", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectionupdaterequest",
            name="processed",
        ),
        migrations.AddField(
            model_name="projectionupdaterequest",
            name="key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectionupdaterequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                ],
                default="processed",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="projectionupdaterequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "processing"])),
                fields=("projection_type", "key"),
                name="unique_projection_update_request",
            ),
        ),
    ]
