# Generated by Django 6.0.5 on 2026-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projections_updater",
            "0002_remove_projectionupdaterequest_processed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectionupdaterequest",
            name="projection_type",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("athlete", "Athlete"),
                    ("tournament", "Tournament"),
                    ("match", "Match"),
                    ("tournament_standing", "Tournament Standing"),
                    ("general_ranking", "General Ranking"),
                    ("modality_ranking", "Modality Ranking"),
                    ("nucleo", "Nucleo"),
                    ("season", "Season"),
                    ("regulation", "Regulation"),
                    ("home_page_config", "Home Page Config"),
                ],
                max_length=255,
            ),
        ),
    ]
