# Generated by Django 6.0.5 on 2026-07-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections_updater", "0003_alter_projectionupdaterequest_projection_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectionupdaterequest",
            name="projection_type",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("athlete", "Athlete"),
                    ("tournament", "Tournament"),
                    ("match", "Match"),
                    ("tournament_standing", "Tournament Standing"),
                    ("general_ranking", "General Ranking"),
                    ("modality_ranking", "Modality Ranking"),
                    ("nucleo", "Nucleo"),
                    ("season", "Season"),
                    ("regulation", "Regulation"),
                    ("home_page_config", "Home Page Config"),
                    ("course", "Course"),
                ],
                max_length=255,
            ),
        ),
    ]
