FROM python:3.11-slim

WORKDIR /app

COPY src/apis/public-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install messaging package
COPY src/shared/rabbitmq-service /tmp/taca-messaging
RUN pip install --no-cache-dir -e /tmp/taca-messaging

COPY src/apis/public-api .

# Run migrations and start the service in dev mode
CMD alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /tmp/taca-messaging --reload-dir /app
