FROM python:3.11-slim

WORKDIR /app

COPY src/apis/public-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/apis/public-api .

# Run migrations and start the service in dev mode
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]
