# Generated by Django 5.2.8 on 2025-12-10 19:08

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("abbreviation", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("logo_url", models.TextField(blank=True, null=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="CourseRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_id", models.UUIDField(db_index=True)),
                ("season_id", models.UUIDField(db_index=True)),
                ("total_points", models.FloatField(default=0.0)),
                ("modality_breakdown", models.JSONField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course Ranking",
                "verbose_name_plural": "Course Rankings",
                "db_table": "course_ranking",
            },
        ),
        migrations.CreateModel(
            name="GeneralRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("season_id", models.UUIDField(db_index=True)),
                ("course_id", models.UUIDField(db_index=True)),
                ("position", models.IntegerField()),
                ("total_points", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "General Ranking",
                "verbose_name_plural": "General Rankings",
                "db_table": "general_ranking",
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tournament_id", models.UUIDField(db_index=True)),
                ("team_home_id", models.UUIDField(db_index=True)),
                ("team_away_id", models.UUIDField(db_index=True)),
                ("location", models.TextField()),
                ("start_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("finished", "Finished"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("home_score", models.IntegerField(blank=True, null=True)),
                ("away_score", models.IntegerField(blank=True, null=True)),
                ("additional_details", models.JSONField(blank=True, null=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Match",
                "verbose_name_plural": "Matches",
                "db_table": "match",
            },
        ),
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("type", models.UUIDField()),
                ("scoring_schema", models.JSONField(blank=True, null=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Modality",
                "verbose_name_plural": "Modalities",
                "db_table": "modality",
            },
        ),
        migrations.CreateModel(
            name="ModalityRanking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modality_id", models.UUIDField(db_index=True)),
                ("season_id", models.UUIDField(db_index=True)),
                ("course_id", models.UUIDField(db_index=True)),
                ("points", models.FloatField(default=0.0)),
                ("details", models.JSONField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modality Ranking",
                "verbose_name_plural": "Modality Rankings",
                "db_table": "modality_ranking",
            },
        ),
        migrations.CreateModel(
            name="ModalityType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("escaloes", models.JSONField(blank=True, null=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Modality Type",
                "verbose_name_plural": "Modality Types",
                "db_table": "modality_type",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("order", models.IntegerField()),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
                "db_table": "stage",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_id", models.UUIDField(db_index=True)),
                ("full_name", models.TextField()),
                ("student_number", models.TextField(unique=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("is_member", models.BooleanField(default=False)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modality_id", models.UUIDField(db_index=True)),
                ("course_id", models.UUIDField(db_index=True)),
                ("name", models.TextField()),
                ("players", models.JSONField(blank=True, null=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "team",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modality_id", models.UUIDField(db_index=True)),
                ("name", models.TextField()),
                ("season_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rules", models.JSONField(blank=True, null=True)),
                ("teams", models.JSONField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("finished_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tournament",
                "verbose_name_plural": "Tournaments",
                "db_table": "tournament",
            },
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("team_id", models.UUIDField(db_index=True)),
                ("player_id", models.UUIDField()),
                ("jersey_number", models.IntegerField()),
                ("is_starter", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_api.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lineup",
                "verbose_name_plural": "Lineups",
                "db_table": "lineup",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("author_id", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_api.match",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "db_table": "comment",
            },
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_api.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journey",
                "verbose_name_plural": "Journeys",
                "db_table": "journey",
            },
        ),
        migrations.AddField(
            model_name="stage",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="admin_api.tournament"
            ),
        ),
    ]
