# Generated by Django 5.2.8 on 2025-12-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modality",
            old_name="type",
            new_name="modality_type_id",
        ),
        migrations.RemoveField(
            model_name="modality",
            name="scoring_schema",
        ),
    ]
