# Generated by Django 5.2.8 on 2025-12-11 01:23

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0002_rename_type_modality_modality_type_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nucleo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("abbreviation", models.TextField(unique=True)),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Nucleo",
                "verbose_name_plural": "Nucleos",
                "db_table": "nucleo",
            },
        ),
    ]
