# Generated by Django 5.2.8 on 2025-12-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0003_nucleo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modality",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
