# Generated by Django 5.2.8 on 2025-12-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0004_alter_modality_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modality",
            name="modality_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.modalitytype",
            ),
        ),
    ]
