# Generated by Django 5.2.8 on 2025-12-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0005_alter_modality_modality_type_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="modality",
            old_name="modality_type_id",
            new_name="modality_type",
        ),
    ]
