# Generated by Django 5.2.8 on 2025-12-11 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0006_rename_modality_type_id_modality_modality_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="course",
            name="nucleo",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.nucleo",
            ),
            preserve_default=False,
        ),
    ]
