# Generated by Django 5.2.8 on 2025-12-14 02:14

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0007_remove_course_description_remove_course_logo_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.TextField()),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "member",
            },
        ),
        migrations.RenameField(
            model_name="student",
            old_name="student_number",
            new_name="enrollment_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="student",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="is_member",
        ),
        migrations.RemoveField(
            model_name="student",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.course",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "member_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="admin_api.member",
                    ),
                ),
                ("staff_number", models.TextField(blank=True, null=True, unique=True)),
                ("contact", models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff Members",
                "db_table": "staff",
            },
            bases=("admin_api.member",),
        ),
        migrations.AddField(
            model_name="student",
            name="member_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="admin_api.member",
            ),
            preserve_default=False,
        ),
    ]
