# Generated by Django 5.2.8 on 2025-12-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0008_member_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="enrollment_number",
            new_name="student_number",
        ),
        migrations.AddField(
            model_name="student",
            name="is_member",
            field=models.BooleanField(default=False),
        ),
    ]
