# Generated by Django 5.2.8 on 2025-12-14 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0009_rename_enrollment_number_student_student_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="course_id",
        ),
        migrations.RemoveField(
            model_name="team",
            name="modality_id",
        ),
        migrations.AddField(
            model_name="team",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="modality",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.modality",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="team",
            name="players",
        ),
        migrations.AddField(
            model_name="team",
            name="players",
            field=models.ManyToManyField(blank=True, to="admin_api.student"),
        ),
    ]
