# Generated by Django 5.2.8 on 2025-12-15 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0010_remove_team_course_id_remove_team_modality_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="modality_id",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="rules",
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="season_id",
        ),
        migrations.AddField(
            model_name="tournament",
            name="modality",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.modality",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="tournament",
            name="teams",
        ),
        migrations.AddField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(blank=True, to="admin_api.team"),
        ),
    ]
