# Generated by Django 5.2.8 on 2025-12-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0011_remove_tournament_modality_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author_id",
            new_name="created_by",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="match",
        ),
        migrations.RemoveField(
            model_name="match",
            name="additional_details",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team_away_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="team_home_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="tournament_id",
        ),
        migrations.AddField(
            model_name="match",
            name="comments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_api.comment",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_away",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="away_matches",
                to="admin_api.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="team_home",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="home_matches",
                to="admin_api.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_api.tournament",
            ),
            preserve_default=False,
        ),
    ]
