# Generated by Django 5.2.8 on 2025-12-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0012_rename_author_id_comment_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="away_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="match",
            name="home_score",
        ),
        migrations.RemoveField(
            model_name="match",
            name="tournament",
        ),
    ]
