# Generated by Django 5.2.8 on 2025-12-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0013_remove_match_away_score_remove_match_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="matches",
            field=models.ManyToManyField(blank=True, to="admin_api.match"),
        ),
    ]
