# Generated by Django 5.2.8 on 2025-12-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0014_tournament_matches"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="matches",
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="matches",
                to="admin_api.tournament",
            ),
        ),
    ]
