# Generated by Django 5.2.8 on 2025-12-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0015_remove_tournament_matches_match_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
