# Generated by Django 5.2.8 on 2025-12-15 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0016_match_away_score_match_home_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineup",
            name="player_id",
        ),
        migrations.RemoveField(
            model_name="lineup",
            name="team_id",
        ),
        migrations.AddField(
            model_name="lineup",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.student",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lineup",
            name="team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="admin_api.team",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lineup",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="admin_api.match"
            ),
        ),
    ]
