# Generated by Django 5.2.8 on 2025-12-15 19:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0017_remove_lineup_player_id_remove_lineup_team_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentRankingPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="admin_api.team"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_positions",
                        to="admin_api.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament Ranking Position",
                "verbose_name_plural": "Tournament Ranking Positions",
                "db_table": "tournament_ranking_position",
                "unique_together": {("tournament", "team")},
            },
        ),
    ]
