"""
Pydantic typed event schemas for the TACA system.

Import individual schemas or use ``EventRegistry`` to look up schemas
by routing key.

    from taca_events.pydantic_schemas import (
        EventRegistry,
        MatchCreatedV1, MatchCreatedData,
        TournamentCreatedV1, TournamentCreatedData,
        ...
    )
"""

from .base import EventSchema
from .matches import (  # Data models; Schema classes
    LineupPlayerData,
    MatchCommentAddedData,
    MatchCommentAddedV1,
    MatchCommentDeletedData,
    MatchCommentDeletedV1,
    MatchCreatedData,
    MatchCreatedV1,
    MatchDeletedData,
    MatchDeletedV1,
    MatchLineupAssignedData,
    MatchLineupAssignedV1,
    MatchParticipantAddedData,
    MatchParticipantAddedV1,
    MatchParticipantData,
    MatchParticipantRemovedData,
    MatchParticipantRemovedV1,
    MatchResultEntryData,
    MatchResultUpdatedData,
    MatchResultUpdatedV1,
    MatchUpdatedData,
    MatchUpdatedV1,
)
from .modalities import (  # Nucleo; Course; ModalityType; Modality; Student; Staff; Team
    CourseCreatedData,
    CourseCreatedV1,
    CourseDeletedData,
    CourseDeletedV1,
    CourseUpdatedData,
    CourseUpdatedV1,
    ModalityCreatedData,
    ModalityCreatedV1,
    ModalityDeletedData,
    ModalityDeletedV1,
    ModalityTypeCreatedData,
    ModalityTypeCreatedV1,
    ModalityTypeDeletedData,
    ModalityTypeDeletedV1,
    ModalityTypeUpdatedData,
    ModalityTypeUpdatedV1,
    ModalityUpdatedData,
    ModalityUpdatedV1,
    NucleoCreatedData,
    NucleoCreatedV1,
    NucleoDeletedData,
    NucleoDeletedV1,
    NucleoUpdatedData,
    NucleoUpdatedV1,
    StaffCreatedData,
    StaffCreatedV1,
    StaffDeletedData,
    StaffDeletedV1,
    StaffUpdatedData,
    StaffUpdatedV1,
    StudentCreatedData,
    StudentCreatedV1,
    StudentDeletedData,
    StudentDeletedV1,
    StudentUpdatedData,
    StudentUpdatedV1,
    TeamCreatedData,
    TeamCreatedV1,
    TeamDeletedData,
    TeamDeletedV1,
    TeamPlayerAddedData,
    TeamPlayerAddedV1,
    TeamPlayerRemovedData,
    TeamPlayerRemovedV1,
    TeamUpdatedData,
    TeamUpdatedV1,
)
from .registry import EventRegistry
from .tournaments import (
    RankingEntryData,
    TournamentCompetitorAddedData,
    TournamentCompetitorAddedV1,
    TournamentCompetitorDeletedData,
    TournamentCompetitorDeletedV1,
    TournamentCreatedData,
    TournamentCreatedV1,
    TournamentDeletedData,
    TournamentDeletedV1,
    TournamentFinishedData,
    TournamentFinishedV1,
    TournamentUpdatedData,
    TournamentUpdatedV1,
)

__all__ = [
    # Base
    "EventSchema",
    "EventRegistry",
    # Match data
    "MatchCreatedData",
    "MatchUpdatedData",
    "MatchDeletedData",
    "MatchParticipantAddedData",
    "MatchParticipantRemovedData",
    "MatchLineupAssignedData",
    "MatchCommentAddedData",
    "MatchCommentDeletedData",
    "MatchResultUpdatedData",
    "MatchParticipantData",
    "LineupPlayerData",
    "MatchResultEntryData",
    # Match schemas
    "MatchCreatedV1",
    "MatchUpdatedV1",
    "MatchDeletedV1",
    "MatchParticipantAddedV1",
    "MatchParticipantRemovedV1",
    "MatchLineupAssignedV1",
    "MatchCommentAddedV1",
    "MatchCommentDeletedV1",
    "MatchResultUpdatedV1",
    # Nucleo
    "NucleoCreatedData",
    "NucleoUpdatedData",
    "NucleoDeletedData",
    "NucleoCreatedV1",
    "NucleoUpdatedV1",
    "NucleoDeletedV1",
    # Course
    "CourseCreatedData",
    "CourseUpdatedData",
    "CourseDeletedData",
    "CourseCreatedV1",
    "CourseUpdatedV1",
    "CourseDeletedV1",
    # ModalityType
    "ModalityTypeCreatedData",
    "ModalityTypeUpdatedData",
    "ModalityTypeDeletedData",
    "ModalityTypeCreatedV1",
    "ModalityTypeUpdatedV1",
    "ModalityTypeDeletedV1",
    # Modality
    "ModalityCreatedData",
    "ModalityUpdatedData",
    "ModalityDeletedData",
    "ModalityCreatedV1",
    "ModalityUpdatedV1",
    "ModalityDeletedV1",
    # Student
    "StudentCreatedData",
    "StudentUpdatedData",
    "StudentDeletedData",
    "StudentCreatedV1",
    "StudentUpdatedV1",
    "StudentDeletedV1",
    # Staff
    "StaffCreatedData",
    "StaffUpdatedData",
    "StaffDeletedData",
    "StaffCreatedV1",
    "StaffUpdatedV1",
    "StaffDeletedV1",
    # Team
    "TeamCreatedData",
    "TeamUpdatedData",
    "TeamDeletedData",
    "TeamPlayerAddedData",
    "TeamPlayerRemovedData",
    "TeamCreatedV1",
    "TeamUpdatedV1",
    "TeamDeletedV1",
    "TeamPlayerAddedV1",
    "TeamPlayerRemovedV1",
    # Tournament data
    "TournamentCreatedData",
    "TournamentUpdatedData",
    "TournamentDeletedData",
    "TournamentFinishedData",
    "TournamentCompetitorAddedData",
    "TournamentCompetitorDeletedData",
    "RankingEntryData",
    # Tournament schemas
    "TournamentCreatedV1",
    "TournamentUpdatedV1",
    "TournamentDeletedV1",
    "TournamentFinishedV1",
    "TournamentCompetitorAddedV1",
    "TournamentCompetitorDeletedV1",
]
