# Generated by Django 6.0.5 on 2026-06-17 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modalities", "0001_initial"),
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Regulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_url", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "modality",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulation",
                        to="modalities.modality",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulations",
                        to="seasons.season",
                    ),
                ),
            ],
        ),
    ]
