# Generated by Django 6.0.5 on 2026-07-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulation",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
