"""init

Revision ID: 001
Revises:
Create Date: 2026-01-12 02:12:42.513686

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=True),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "IN_PROGRESS", "FINISHED", "CANCELLED", name="match_status"
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_match_tournament_id"),
        "match",
        ["tournament_id"],
        unique=False,
        schema="matches",
    )
    op.create_table(
        "outbox_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_outbox_event_aggregate_id"),
        "outbox_event",
        ["aggregate_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_outbox_event_aggregate_type"),
        "outbox_event",
        ["aggregate_type"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_outbox_event_event_type"),
        "outbox_event",
        ["event_type"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_outbox_event_published"),
        "outbox_event",
        ["published"],
        unique=False,
        schema="matches",
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_comment_match_id"),
        "comment",
        ["match_id"],
        unique=False,
        schema="matches",
    )
    op.create_table(
        "lineup",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("jersey_number", sa.Integer(), nullable=False),
        sa.Column("is_starter", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_lineup_match_id"),
        "lineup",
        ["match_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_lineup_player_id"),
        "lineup",
        ["player_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_lineup_team_id"),
        "lineup",
        ["team_id"],
        unique=False,
        schema="matches",
    )
    op.create_table(
        "match_participant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column(
            "participant_type",
            sa.Enum("TEAM", "ATHLETE", name="participant_type"),
            nullable=False,
        ),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column("athlete_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("result_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_match_participant_athlete_id"),
        "match_participant",
        ["athlete_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_match_participant_match_id"),
        "match_participant",
        ["match_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_match_participant_team_id"),
        "match_participant",
        ["team_id"],
        unique=False,
        schema="matches",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_matches_match_participant_team_id"),
        table_name="match_participant",
        schema="matches",
    )
    op.drop_index(
        op.f("ix_matches_match_participant_match_id"),
        table_name="match_participant",
        schema="matches",
    )
    op.drop_index(
        op.f("ix_matches_match_participant_athlete_id"),
        table_name="match_participant",
        schema="matches",
    )
    op.drop_table("match_participant", schema="matches")
    op.drop_index(
        op.f("ix_matches_lineup_team_id"), table_name="lineup", schema="matches"
    )
    op.drop_index(
        op.f("ix_matches_lineup_player_id"), table_name="lineup", schema="matches"
    )
    op.drop_index(
        op.f("ix_matches_lineup_match_id"), table_name="lineup", schema="matches"
    )
    op.drop_table("lineup", schema="matches")
    op.drop_index(
        op.f("ix_matches_comment_match_id"), table_name="comment", schema="matches"
    )
    op.drop_table("comment", schema="matches")
    op.drop_index(
        op.f("ix_matches_outbox_event_published"),
        table_name="outbox_event",
        schema="matches",
    )
    op.drop_index(
        op.f("ix_matches_outbox_event_event_type"),
        table_name="outbox_event",
        schema="matches",
    )
    op.drop_index(
        op.f("ix_matches_outbox_event_aggregate_type"),
        table_name="outbox_event",
        schema="matches",
    )
    op.drop_index(
        op.f("ix_matches_outbox_event_aggregate_id"),
        table_name="outbox_event",
        schema="matches",
    )
    op.drop_table("outbox_event", schema="matches")
    op.drop_index(
        op.f("ix_matches_match_tournament_id"), table_name="match", schema="matches"
    )
    op.drop_table("match", schema="matches")
    # ### end Alembic commands ###
