"""init

Revision ID: 250f15703de3
Revises:
Create Date: 2025-12-01 16:41:43.641500

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "250f15703de3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("modality_id", sa.UUID(), nullable=False),
        sa.Column("team_a_id", sa.UUID(), nullable=False),
        sa.Column("team_b_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("SCHEDULED", "FINISHED", "CANCELED", name="gamestate"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_game_modality_id"),
        "game",
        ["modality_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_game_tournament_id"),
        "game",
        ["tournament_id"],
        unique=False,
        schema="matches",
    )
    op.create_table(
        "result",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("team_a_score", sa.Integer(), nullable=False),
        sa.Column("team_b_score", sa.Integer(), nullable=False),
        sa.Column("submitted_by", sa.UUID(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["matches.game.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_result_game_id"),
        "result",
        ["game_id"],
        unique=False,
        schema="matches",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_matches_result_game_id"), table_name="result", schema="matches"
    )
    op.drop_table("result", schema="matches")
    op.drop_index(
        op.f("ix_matches_game_tournament_id"), table_name="game", schema="matches"
    )
    op.drop_index(
        op.f("ix_matches_game_modality_id"), table_name="game", schema="matches"
    )
    op.drop_table("game", schema="matches")
    # ### end Alembic commands ###
