"""modules update

Revision ID: bd3864970798
Revises: 250f15703de3
Create Date: 2025-12-06 01:06:44.560237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bd3864970798"
down_revision: Union[str, Sequence[str], None] = "250f15703de3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("team_home_id", sa.UUID(), nullable=False),
        sa.Column("team_away_id", sa.UUID(), nullable=False),
        sa.Column("location", sa.Text(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SCHEDULED", "IN_PROGRESS", "FINISHED", "CANCELLED", name="matchstatus"
            ),
            nullable=False,
        ),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("additional_details", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_match_team_away_id"),
        "match",
        ["team_away_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_match_team_home_id"),
        "match",
        ["team_home_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_match_tournament_id"),
        "match",
        ["tournament_id"],
        unique=False,
        schema="matches",
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_comment_match_id"),
        "comment",
        ["match_id"],
        unique=False,
        schema="matches",
    )
    op.create_table(
        "lineup",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("jersey_number", sa.Integer(), nullable=False),
        sa.Column("is_starter", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_lineup_match_id"),
        "lineup",
        ["match_id"],
        unique=False,
        schema="matches",
    )
    op.create_index(
        op.f("ix_matches_lineup_team_id"),
        "lineup",
        ["team_id"],
        unique=False,
        schema="matches",
    )
    op.execute("DROP TABLE IF EXISTS matches.game CASCADE;")
    op.execute("DROP TABLE IF EXISTS matches.result CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "result",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("game_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("team_a_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("team_b_score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("submitted_by", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "submitted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["matches.game.id"], name=op.f("result_game_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("result_pkey")),
        schema="matches",
    )
    op.create_table(
        "game",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tournament_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("modality_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("team_a_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("team_b_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "scheduled_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("location", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "state",
            postgresql.ENUM("SCHEDULED", "FINISHED", "CANCELED", name="gamestate"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("game_pkey")),
        schema="matches",
    )
    op.drop_index(
        op.f("ix_matches_lineup_team_id"), table_name="lineup", schema="matches"
    )
    op.drop_index(
        op.f("ix_matches_lineup_match_id"), table_name="lineup", schema="matches"
    )
    op.drop_table("lineup", schema="matches")
    op.drop_index(
        op.f("ix_matches_comment_match_id"), table_name="comment", schema="matches"
    )
    op.drop_table("comment", schema="matches")
    op.drop_index(
        op.f("ix_matches_match_tournament_id"), table_name="match", schema="matches"
    )
    op.drop_index(
        op.f("ix_matches_match_team_home_id"), table_name="match", schema="matches"
    )
    op.drop_index(
        op.f("ix_matches_match_team_away_id"), table_name="match", schema="matches"
    )
    op.drop_table("match", schema="matches")
    # ### end Alembic commands ###
