FROM python:3.11-slim

WORKDIR /app

COPY src/microservices/tournaments-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install messaging package
COPY src/shared/taca-messaging /tmp/taca-messaging
RUN pip install --no-cache-dir -e /tmp/taca-messaging

# Install logging package
COPY src/shared/taca-logging /tmp/taca-logging
RUN pip install --no-cache-dir -e /tmp/taca-logging

# Install event package
COPY src/shared/taca-events /tmp/taca-events
RUN pip install --no-cache-dir -e /tmp/taca-events

COPY src/microservices/tournaments-service .

# Run migrations and start the service in dev mode
CMD alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /tmp/taca-messaging --reload-dir /app
