"""
Django settings for competition_api project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from admin_api.logging_config import configure_logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "default-dev-key-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "localhost",
    "competition-api",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "django_prometheus",
    "admin_api",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "admin_api.middleware.StructlogMiddleware",  # Structured logging context
    "admin_api.middleware.KeycloakJWTMiddleware",  # JWT validation & user/role extraction
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "loki": {
            "class": "logging_loki.LokiHandler",
            "url": "http://loki:3100/loki/api/v1/push",
            "tags": {"application": "competition-api", "job": "competition-api"},
            "version": "1",
        },
    },
    "root": {
        "handlers": ["console", "loki"],
        "level": "INFO",
    },
}

ROOT_URLCONF = "competition_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "competition_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "taca_ua"),
        "USER": os.environ.get("POSTGRES_USER", "user"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "password"),
        "HOST": os.environ.get("POSTGRES_HOST", "postgres"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "OPTIONS": {"options": "-c search_path=general"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_ROUTER_TRAILING_SLASH": False,
}
APPEND_SLASH = True

# DRF Spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Competition API (Admin API)",
    "DESCRIPTION": "API for managing TACA competitions - used by administrators",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/admin",
}

# MinIO Configuration
MINIO_ENDPOINT = os.environ.get("MINIO_ENDPOINT", "minio:9000")
MINIO_ROOT_USER = os.environ.get("MINIO_ROOT_USER", "admin")
MINIO_ROOT_PASSWORD = os.environ.get("MINIO_ROOT_PASSWORD", "adminadmin")
MINIO_USE_SSL = os.environ.get("MINIO_USE_SSL", "false").lower() == "true"

# File Upload Settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB

MINIO_PUBLIC_ENDPOINT = os.environ.get(
    "MINIO_PUBLIC_ENDPOINT", "http://localhost/files"
)

# ---------------------------------------------------------------------------
# Keycloak / JWT Configuration
# ---------------------------------------------------------------------------

# Internal URL used to reach Keycloak over the Docker network (never exposed to
# clients).  Includes KC_HTTP_RELATIVE_PATH (/keycloak) set in docker-compose.
KEYCLOAK_INTERNAL_URL = os.environ.get(
    "KEYCLOAK_INTERNAL_URL", "http://keycloak:8080/keycloak"
)

# Realm name — must match the realm configured in Keycloak.
KEYCLOAK_REALM = os.environ.get("KEYCLOAK_REALM", "taca-ua")

# JWKS endpoint — fetched over the internal Docker network (no nginx hop).
KEYCLOAK_JWKS_URI = (
    f"{KEYCLOAK_INTERNAL_URL}/realms/{KEYCLOAK_REALM}/protocol/openid-connect/certs"
)

# Expected ``iss`` claim in the JWT.  Tokens are issued by Keycloak using the
# external URL seen by the browser (through nginx), so this must be the public
# base URL — NOT the internal Docker URL.
KEYCLOAK_ISSUER = os.environ.get(
    "KEYCLOAK_ISSUER",
    f"{KEYCLOAK_INTERNAL_URL}/realms/{KEYCLOAK_REALM}",  # fallback for local dev without nginx
)

# Accepted signing algorithms.  Keycloak defaults to RS256.
KEYCLOAK_ALGORITHMS = ["RS256"]

# Optional: set to the Keycloak client_id (or resource server name) to enforce
# audience verification.  The bearer-only client for this API is
# "competition-api-gateway".  Tokens are issued by "frontend-admin" and do not
# contain "competition-api-gateway" in their ``aud`` claim unless an explicit
# audience mapper is configured in Keycloak, so verification is off by default.
KEYCLOAK_AUDIENCE = os.environ.get("KEYCLOAK_AUDIENCE", None)

# Paths that bypass JWT validation entirely (no Authorization header required).
# Add any public / infrastructure endpoints here.
KEYCLOAK_EXEMPT_PATHS = [
    "/api/admin/schema/",  # OpenAPI schema
    "/api/admin/docs/",  # Swagger UI
    "/api/admin/redoc/",  # ReDoc UI
    "/api/admin/auth/",  # Keycloak-based login helpers (if any)
    "/metrics",  # Prometheus scrape endpoint
    "/health/",  # Health-check
    "/admin/",  # Django admin (uses its own session auth)
]

# ---------------------------------------------------------------------------
# DEV Auth Bypass
# ---------------------------------------------------------------------------
# WARNING: Only for local development / scripted testing.  Never set
# DEV_AUTH_BYPASS_ENABLED=true in production.
#
# To use, send the header:  X-Dev-Auth-Token: <DEV_AUTH_BYPASS_TOKEN>
# The request is then treated as authenticated with the configured roles.
#
# Example env block in docker-compose.dev.yml:
#   DEV_AUTH_BYPASS_ENABLED: "true"
#   DEV_AUTH_BYPASS_TOKEN: "super-secret-dev-token"
#   DEV_AUTH_BYPASS_ROLES: "general_admin"   # comma-separated

DEV_AUTH_BYPASS_ENABLED: bool = (
    os.environ.get("DEV_AUTH_BYPASS_ENABLED", "false").lower() == "true"
)
DEV_AUTH_BYPASS_TOKEN: str = os.environ.get("DEV_AUTH_BYPASS_TOKEN", "")
_raw_roles = os.environ.get("DEV_AUTH_BYPASS_ROLES", "general_admin")
DEV_AUTH_BYPASS_ROLES: list[str] = [
    r.strip() for r in _raw_roles.split(",") if r.strip()
]

# ---------------------------------------------------------------------------
# Initialize structured logging
# ---------------------------------------------------------------------------
configure_logging(
    service_name="competition-api",
    log_level=os.environ.get("LOG_LEVEL", "INFO"),
)
