# Generated by Django 6.0.5 on 2026-06-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicWebsiteHomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("_bucket", models.IntegerField(verbose_name=1)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the home page", max_length=255
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        help_text="Subtitle of the home page", max_length=255
                    ),
                ),
                (
                    "welcome_message",
                    models.CharField(
                        help_text="Welcome message for the home page", max_length=255
                    ),
                ),
                (
                    "about_us",
                    models.TextField(help_text="About us section for the home page"),
                ),
                (
                    "hero_image_url",
                    models.URLField(
                        help_text="URL of the hero image for the home page"
                    ),
                ),
            ],
            options={
                "unique_together": {("_bucket",)},
            },
        ),
    ]
