# Generated by Django 6.0.5 on 2026-06-26 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataform_configs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the sponsor", max_length=255),
                ),
                ("logo_url", models.URLField(help_text="URL of the sponsor's logo")),
                (
                    "website_url",
                    models.URLField(help_text="URL of the sponsor's website"),
                ),
                (
                    "conf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="plataform_configs.publicwebsitehomepage",
                    ),
                ),
            ],
            options={
                "unique_together": {("conf", "name")},
            },
        ),
    ]
