# Generated by Django 6.0.5 on 2026-06-17 19:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("modality_types", "0001_initial"),
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SeasonModality",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modality_seasons",
                        to="modalities.modality",
                    ),
                ),
                (
                    "modality_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_modalities",
                        to="modality_types.modalitytype",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_modalities",
                        to="seasons.season",
                    ),
                ),
            ],
            options={
                "unique_together": {("season", "modality", "modality_type")},
            },
        ),
    ]
