# Generated by Django 6.0.5 on 2026-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modalities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modality",
            name="point_unit",
            field=models.CharField(default="point", max_length=255),
        ),
    ]
