"""
TACA Events Schema Registry

Centralized event schema definitions and validation for the TACA system.

New typed Pydantic schemas are available via ``taca_events.pydantic_schemas``:

    from taca_events.pydantic_schemas import (
        EventRegistry,
        MatchCreatedV1, MatchCreatedData,
        ...
    )
"""

from .builder import EventBuilder

# Typed Pydantic schemas – new event system
from .pydantic_schemas import (  # Match schemas; Nucleo schemas; Course schemas; ModalityType schemas; Modality schemas; Student schemas; Staff schemas; Team schemas; Tournament schemas
    CourseCreatedData,
    CourseCreatedV1,
    CourseDeletedData,
    CourseDeletedV1,
    CourseUpdatedData,
    CourseUpdatedV1,
    EventRegistry,
    EventSchema,
    LineupPlayerData,
    MatchCommentAddedData,
    MatchCommentAddedV1,
    MatchCommentDeletedData,
    MatchCommentDeletedV1,
    MatchCreatedData,
    MatchCreatedV1,
    MatchDeletedData,
    MatchDeletedV1,
    MatchLineupAssignedData,
    MatchLineupAssignedV1,
    MatchParticipantAddedData,
    MatchParticipantAddedV1,
    MatchParticipantData,
    MatchParticipantRemovedData,
    MatchParticipantRemovedV1,
    MatchResultEntryData,
    MatchResultUpdatedData,
    MatchResultUpdatedV1,
    MatchUpdatedData,
    MatchUpdatedV1,
    ModalityCreatedData,
    ModalityCreatedV1,
    ModalityDeletedData,
    ModalityDeletedV1,
    ModalityTypeCreatedData,
    ModalityTypeCreatedV1,
    ModalityTypeDeletedData,
    ModalityTypeDeletedV1,
    ModalityTypeUpdatedData,
    ModalityTypeUpdatedV1,
    ModalityUpdatedData,
    ModalityUpdatedV1,
    NucleoCreatedData,
    NucleoCreatedV1,
    NucleoDeletedData,
    NucleoDeletedV1,
    NucleoUpdatedData,
    NucleoUpdatedV1,
    RankingEntryData,
    StaffCreatedData,
    StaffCreatedV1,
    StaffDeletedData,
    StaffDeletedV1,
    StaffUpdatedData,
    StaffUpdatedV1,
    StudentCreatedData,
    StudentCreatedV1,
    StudentDeletedData,
    StudentDeletedV1,
    StudentUpdatedData,
    StudentUpdatedV1,
    TeamCreatedData,
    TeamCreatedV1,
    TeamDeletedData,
    TeamDeletedV1,
    TeamPlayerAddedData,
    TeamPlayerAddedV1,
    TeamPlayerRemovedData,
    TeamPlayerRemovedV1,
    TeamUpdatedData,
    TeamUpdatedV1,
    TournamentCompetitorAddedData,
    TournamentCompetitorAddedV1,
    TournamentCompetitorDeletedData,
    TournamentCompetitorDeletedV1,
    TournamentCreatedData,
    TournamentCreatedV1,
    TournamentDeletedData,
    TournamentDeletedV1,
    TournamentFinishedData,
    TournamentFinishedV1,
    TournamentUpdatedData,
    TournamentUpdatedV1,
)
from .registry import SchemaRegistry
from .types import EventType, RoutingKeys
from .validator import validate_event, validate_event_data

__all__ = [
    # Legacy (kept for backward compatibility)
    "EventBuilder",
    "EventType",
    "RoutingKeys",
    "SchemaRegistry",
    "validate_event",
    "validate_event_data",
    # New typed event system
    "EventSchema",
    "EventRegistry",
    "LineupPlayerData",
    # Match
    "MatchCreatedV1",
    "MatchCreatedData",
    "MatchUpdatedV1",
    "MatchUpdatedData",
    "MatchDeletedV1",
    "MatchDeletedData",
    "MatchParticipantAddedV1",
    "MatchParticipantAddedData",
    "MatchParticipantRemovedV1",
    "MatchParticipantRemovedData",
    "MatchLineupAssignedV1",
    "MatchLineupAssignedData",
    "MatchCommentAddedV1",
    "MatchCommentAddedData",
    "MatchCommentDeletedV1",
    "MatchCommentDeletedData",
    "MatchResultUpdatedV1",
    "MatchResultUpdatedData",
    "MatchParticipantData",
    "MatchResultEntryData",
    "LineupPlayerData",
    # Nucleo
    "NucleoCreatedV1",
    "NucleoCreatedData",
    "NucleoUpdatedV1",
    "NucleoUpdatedData",
    "NucleoDeletedV1",
    "NucleoDeletedData",
    # Course
    "CourseCreatedV1",
    "CourseCreatedData",
    "CourseUpdatedV1",
    "CourseUpdatedData",
    "CourseDeletedV1",
    "CourseDeletedData",
    # ModalityType
    "ModalityTypeCreatedV1",
    "ModalityTypeCreatedData",
    "ModalityTypeUpdatedV1",
    "ModalityTypeUpdatedData",
    "ModalityTypeDeletedV1",
    "ModalityTypeDeletedData",
    # Modality
    "ModalityCreatedV1",
    "ModalityCreatedData",
    "ModalityUpdatedV1",
    "ModalityUpdatedData",
    "ModalityDeletedV1",
    "ModalityDeletedData",
    # Student
    "StudentCreatedV1",
    "StudentCreatedData",
    "StudentUpdatedV1",
    "StudentUpdatedData",
    "StudentDeletedV1",
    "StudentDeletedData",
    # Staff
    "StaffCreatedV1",
    "StaffCreatedData",
    "StaffUpdatedV1",
    "StaffUpdatedData",
    "StaffDeletedV1",
    "StaffDeletedData",
    # Team
    "TeamCreatedV1",
    "TeamCreatedData",
    "TeamUpdatedV1",
    "TeamUpdatedData",
    "TeamDeletedV1",
    "TeamDeletedData",
    "TeamPlayerAddedV1",
    "TeamPlayerAddedData",
    "TeamPlayerRemovedV1",
    "TeamPlayerRemovedData",
    # Tournament
    "TournamentCreatedV1",
    "TournamentCreatedData",
    "TournamentUpdatedV1",
    "TournamentUpdatedData",
    "TournamentDeletedV1",
    "TournamentDeletedData",
    "TournamentFinishedV1",
    "TournamentFinishedData",
    "TournamentCompetitorAddedV1",
    "TournamentCompetitorAddedData",
    "TournamentCompetitorDeletedV1",
    "TournamentCompetitorDeletedData",
    "RankingEntryData",
]

__version__ = "1.0.0"
