FROM python:3.11-slim

WORKDIR /app

COPY src/shared /tmp

COPY src/microservices/ranking-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/microservices/ranking-service .

# Run migrations and start the service in dev mode
CMD alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /tmp --reload-dir /app
