# Generated by Django 6.0.5 on 2026-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finished_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
