# Generated by Django 6.0.5 on 2026-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nucleus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("general_admin", "General Admin"),
                            ("nucleo_admin", "Nucleo Admin"),
                        ],
                        max_length=255,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "nucleos",
                    models.ManyToManyField(
                        blank=True, related_name="admins", to="nucleus.nucleus"
                    ),
                ),
            ],
        ),
    ]
