# Generated by Django 6.0.5 on 2026-05-30 21:35

from config.settings import DEFAULT_SEASON_NAME
from django.db import migrations, models


def create_initial_season(apps, schema_editor):
    Season = apps.get_model("apps", "Season")
    Season.objects.create(name=DEFAULT_SEASON_NAME, is_current=True)


def delete_initial_season(apps, schema_editor):
    Season = apps.get_model("apps", "Season")
    Season.objects.filter(name=DEFAULT_SEASON_NAME).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("is_current", models.BooleanField(default=False)),
                ("start_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finished_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RunPython(create_initial_season, delete_initial_season),
    ]
