# Generated by Django 6.0.5 on 2026-05-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="is_current",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
