# Generated by Django 6.0.5 on 2026-06-02 18:41

import uuid

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_modality_seasonmodality"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nucleus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=100)),
                ("logo_url", models.URLField(blank=True, null=True)),
                (
                    "admins_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), blank=True, default=list
                    ),
                ),
            ],
            options={
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["admins_ids"], name="apps_nucleu_admins__05a353_gin"
                    )
                ],
            },
        ),
    ]
