# Generated by Django 6.0.5 on 2026-06-02 19:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_nucleus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=100)),
                (
                    "nucleus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="apps.nucleus",
                    ),
                ),
                (
                    "seasons",
                    models.ManyToManyField(related_name="courses", to="apps.season"),
                ),
            ],
        ),
    ]
