# Generated by Django 6.0.5 on 2026-06-02 23:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_athlete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "staff_number",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
