# Generated by Django 6.0.5 on 2026-06-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0010_regulation"),
        ("apps", "0010_tournament_tournamentcompetitor_tournamentresult"),
    ]

    operations = []
