# Generated by Django 6.0.5 on 2026-06-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0011_merge_20260605_1407"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeagueSettings",
            fields=[
                (
                    "tournament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="apps.tournament",
                    ),
                ),
                ("win_points", models.PositiveIntegerField(default=3)),
                ("draw_points", models.PositiveIntegerField(default=1)),
                ("loss_points", models.PositiveIntegerField(default=0)),
                (
                    "draw_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("goal_difference", "Goal Difference"),
                            ("goals_scored", "Goals Scored"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="athlete",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="athletes",
                to="apps.course",
            ),
        ),
        migrations.AlterField(
            model_name="modalitytype",
            name="tournament_competitor_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("team", "Team")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="seasonmodality",
            name="modality_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_modalities",
                to="apps.modalitytype",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="competitor_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("team", "Team")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LeagueStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("played", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("points_for", models.PositiveIntegerField(default=0)),
                ("points_against", models.PositiveIntegerField(default=0)),
                ("league_points", models.PositiveIntegerField(default=0)),
                (
                    "competitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.tournamentcompetitor",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("tournament", "competitor")},
            },
        ),
    ]
