# Generated by Django 6.0.5 on 2026-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0012_leaguesettings_alter_athlete_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournament_format",
            field=models.CharField(
                choices=[("free", "Free"), ("league", "League")],
                default="free",
                max_length=20,
            ),
        ),
    ]
