# Generated by Django 6.0.5 on 2026-06-05 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0013_tournament_tournament_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentcompetitor",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.athlete",
            ),
        ),
        migrations.AddField(
            model_name="tournamentcompetitor",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentcompetitor",
            unique_together={("tournament", "team", "athlete")},
        ),
        migrations.AlterField(
            model_name="leaguesettings",
            name="draw_rule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("points_difference", "Points Difference"),
                    ("points_scored", "Points Scored"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="tournamentcompetitor",
            name="competitor_id",
        ),
    ]
