# Generated by Django 6.0.5 on 2026-06-05 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0014_alter_leaguesettings_draw_rule_match_matchcomment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentcompetitor",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.athlete",
            ),
        ),
        migrations.AddField(
            model_name="tournamentcompetitor",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentcompetitor",
            unique_together={("tournament", "team", "athlete")},
        ),
        migrations.RemoveField(
            model_name="tournamentcompetitor",
            name="competitor_id",
        ),
    ]
