# Generated by Django 6.0.5 on 2026-06-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_match_matchcomment_matchparticipant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchparticipantathletelineup",
            name="match_participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineup",
                to="apps.matchparticipant",
            ),
        ),
    ]
