# Generated by Django 6.0.5 on 2026-06-06 22:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0016_alter_matchparticipantathletelineup_match_participant"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchParticipantStaffAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="apps.matchparticipant",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_assignments",
                        to="apps.staff",
                    ),
                ),
            ],
            options={
                "unique_together": {("match_participant", "staff")},
            },
        ),
    ]
