# Generated by Django 6.0.5 on 2026-06-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0017_matchparticipantstaffassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modalitytype",
            name="tournament_competitor_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("team", "Team")],
                max_length=20,
                null=True,
            ),
        ),
    ]
