# Generated by Django 6.0.5 on 2026-06-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0019_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
