# Generated by Django 6.0.5 on 2026-06-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0020_admin_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaguesettings",
            name="tournament",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="league_settings",
                serialize=False,
                to="apps.tournament",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaguestanding",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="leaguestanding",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="leaguestanding",
            name="id",
        ),
        migrations.RemoveField(
            model_name="leaguestanding",
            name="tournament",
        ),
        migrations.AlterField(
            model_name="leaguestanding",
            name="competitor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="apps.tournamentcompetitor",
            ),
        ),
    ]
