# Generated by Django 6.0.5 on 2026-06-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0021_alter_leaguestanding_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="apps.course",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="modality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="apps.modality",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="apps.season",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournaments",
                to="apps.season",
            ),
        ),
        migrations.CreateModel(
            name="CourseTournamentPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.course"
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.modality"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apps.season"
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps.tournament",
                    ),
                ),
            ],
            options={
                "unique_together": {("season", "course", "modality", "tournament")},
            },
        ),
    ]
