"""init

Revision ID: 9c2d6e7664af
Revises:
Create Date: 2025-12-01 16:54:43.861548

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c2d6e7664af"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games_view",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("tournament_name", sa.Text(), nullable=True),
        sa.Column("modality_name", sa.Text(), nullable=True),
        sa.Column("team_a_name", sa.Text(), nullable=True),
        sa.Column("team_b_name", sa.Text(), nullable=True),
        sa.Column("score", sa.Text(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("game_id"),
        schema="public_read",
    )
    op.create_table(
        "ranking_view",
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("team", sa.Text(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tournament_id", "team"),
        schema="public_read",
    )
    op.create_table(
        "tournament_view",
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("modality", sa.Text(), nullable=True),
        sa.Column("stage_count", sa.Integer(), nullable=True),
        sa.Column("total_matches", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("tournament_id"),
        schema="public_read",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tournament_view", schema="public_read")
    op.drop_table("ranking_view", schema="public_read")
    op.drop_table("games_view", schema="public_read")
    # ### end Alembic commands ###
