FROM python:3.11-slim

WORKDIR /app

# Esta linha já copia a pasta shared (onde estão events, logging, storage, etc.)
COPY src/shared /tmp

COPY src/microservices/modalities-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Removemos as instalações manuais da HEAD. 
# A dev gere isso de forma automática agora.

COPY src/microservices/modalities-service .

# Run migrations and start the service in dev mode
CMD alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /tmp --reload-dir /app