# Generated by Django 6.0.5 on 2026-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RankingRecomputationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_id", models.UUIDField(blank=True, null=True)),
                ("modality_id", models.UUIDField(blank=True, null=True)),
                ("modality_type_id", models.UUIDField(blank=True, null=True)),
                ("tournament_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
