# Generated by Django 6.0.5 on 2026-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking_updater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingrecomputationrequest",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
