# Generated by Django 6.0.5 on 2026-07-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleus", "0001_initial"),
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleus",
            name="seasons",
            field=models.ManyToManyField(related_name="nuclei", to="seasons.season"),
        ),
    ]
