# Generated by Django 6.0.5 on 2026-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nucleus", "0002_nucleus_seasons"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="nucleus",
            name="nucleus_nuc_admins__5e36a0_gin",
        ),
        migrations.AddField(
            model_name="nucleus",
            name="entity_type",
            field=models.CharField(
                choices=[("nucleus", "Núcleo"), ("external", "Externo")],
                default="nucleus",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="nucleus",
            name="admins_ids",
        ),
    ]
