FROM python:3.11-slim

WORKDIR /app

COPY src/apis/competiotion-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install messaging package
COPY src/shared/taca-messaging /tmp/taca-messaging
RUN pip install --no-cache-dir -e /tmp/taca-messaging

# Install logging package
COPY src/shared/taca-logging /tmp/taca-logging
RUN pip install --no-cache-dir -e /tmp/taca-logging

COPY src/apis/competiotion-api .

CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]
