# Generated by Django 6.0.5 on 2026-06-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralRankingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_id", models.IntegerField()),
                ("course_id", models.UUIDField()),
                ("course_name", models.CharField(max_length=255)),
                ("course_abbreviation", models.CharField(max_length=255)),
                ("nucleo_id", models.UUIDField()),
                ("nucleo_name", models.CharField(max_length=255)),
                ("nucleo_abbreviation", models.CharField(max_length=255)),
                ("points", models.IntegerField()),
                ("rank", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["season_id"], name="projections_season__beac2c_idx"
                    ),
                    models.Index(fields=["rank"], name="projections_rank_4c594f_idx"),
                    models.Index(
                        fields=["course_id"], name="projections_course__3a5920_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchDetailView",
            fields=[
                ("match_id", models.UUIDField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("start_time", models.DateTimeField()),
                ("tournament_id", models.UUIDField()),
                ("tournament_name", models.CharField(max_length=255)),
                ("modality_id", models.UUIDField()),
                ("modality_name", models.CharField(max_length=255)),
                ("participants", models.JSONField()),
                ("results", models.JSONField()),
                ("participant_count", models.IntegerField()),
                ("comment_count", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="projections_status_47e7b2_idx"
                    ),
                    models.Index(
                        fields=["start_time"], name="projections_start_t_0990f5_idx"
                    ),
                    models.Index(
                        fields=["tournament_id"], name="projections_tournam_bbd146_idx"
                    ),
                    models.Index(
                        fields=["modality_id"], name="projections_modalit_238989_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModalityRankingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_id", models.IntegerField()),
                ("modality_id", models.UUIDField()),
                ("modality_name", models.CharField(max_length=255)),
                ("course_id", models.UUIDField()),
                ("course_name", models.CharField(max_length=255)),
                ("course_abbreviation", models.CharField(max_length=255)),
                ("nucleo_id", models.UUIDField()),
                ("nucleo_name", models.CharField(max_length=255)),
                ("nucleo_abbreviation", models.CharField(max_length=255)),
                ("points", models.IntegerField()),
                ("rank", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["season_id"], name="projections_season__bcb378_idx"
                    ),
                    models.Index(
                        fields=["modality_id"], name="projections_modalit_e40ab1_idx"
                    ),
                    models.Index(fields=["rank"], name="projections_rank_8b87ff_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NucleoDetailView",
            fields=[
                ("nucleo_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=255)),
                ("logo_url", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["nucleo_id"], name="projections_nucleo__303a4b_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SeasonDetailView",
            fields=[
                ("season_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["season_id"], name="projections_season__c67c7f_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentDetailView",
            fields=[
                ("student_id", models.UUIDField(primary_key=True, serialize=False)),
                ("student_number", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=255)),
                ("is_member", models.BooleanField()),
                ("course_id", models.UUIDField()),
                ("course_name", models.CharField(max_length=255)),
                ("course_abbreviation", models.CharField(max_length=255)),
                ("nucleo_id", models.UUIDField()),
                ("nucleo_name", models.CharField(max_length=255)),
                ("nucleo_abbreviation", models.CharField(max_length=255)),
                ("team_count", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["course_id"], name="projections_course__35f3aa_idx"
                    ),
                    models.Index(
                        fields=["nucleo_id"], name="projections_nucleo__325706_idx"
                    ),
                    models.Index(
                        fields=["student_number"], name="projections_student_8ed342_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TeamDetailView",
            fields=[
                ("team_id", models.UUIDField(primary_key=True, serialize=False)),
                ("team_name", models.CharField(max_length=255)),
                ("teams_season_id", models.IntegerField()),
                ("course_id", models.UUIDField()),
                ("course_name", models.CharField(max_length=255)),
                ("course_abbreviation", models.CharField(max_length=255)),
                ("nucleo_id", models.UUIDField()),
                ("nucleo_name", models.CharField(max_length=255)),
                ("nucleo_abbreviation", models.CharField(max_length=255)),
                ("nucleo_logo_url", models.CharField(max_length=255)),
                ("modality_id", models.UUIDField()),
                ("modality_name", models.CharField(max_length=255)),
                ("modality_type_id", models.UUIDField()),
                ("modality_type_name", models.CharField(max_length=255)),
                ("player_count", models.IntegerField()),
                ("players", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["course_id"], name="projections_course__bfb4b5_idx"
                    ),
                    models.Index(
                        fields=["nucleo_id"], name="projections_nucleo__669847_idx"
                    ),
                    models.Index(
                        fields=["modality_id"], name="projections_modalit_098f2a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TournamentDetailView",
            fields=[
                ("tournament_id", models.UUIDField(primary_key=True, serialize=False)),
                ("tournament_name", models.CharField(max_length=255)),
                ("tournament_season_id", models.IntegerField()),
                ("start_date", models.DateField()),
                ("status", models.CharField(max_length=255)),
                ("modality_id", models.UUIDField()),
                ("modality_name", models.CharField(max_length=255)),
                ("modality_type_id", models.UUIDField()),
                ("modality_type_name", models.CharField(max_length=255)),
                ("competitor_count", models.IntegerField()),
                ("match_count", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="projections_status_3a1a0f_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="projections_start_d_cd61ec_idx"
                    ),
                    models.Index(
                        fields=["modality_id"], name="projections_modalit_c583e5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TournamentStandingsView",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "tournament_id",
                        "competitor_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tournament_id", models.UUIDField()),
                ("competitor_id", models.UUIDField()),
                ("competitor_type", models.CharField(max_length=255)),
                ("competitor_entity_id", models.UUIDField()),
                ("competitor_name", models.CharField(max_length=255)),
                ("position", models.IntegerField()),
                ("statistics_metadata", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tournament_id"], name="projections_tournam_b29b95_idx"
                    )
                ],
            },
        ),
    ]
