# Generated by Django 6.0.5 on 2026-06-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentstandingsview",
            name="statistics_metadata",
            field=models.JSONField(default=None, null=True),
        ),
    ]
