# Generated by Django 6.0.5 on 2026-06-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0002_alter_tournamentstandingsview_statistics_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalrankingview",
            name="tournaments_participated",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
