# Generated by Django 6.0.5 on 2026-06-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0003_generalrankingview_tournaments_participated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamdetailview",
            old_name="teams_season_id",
            new_name="team_season_id",
        ),
    ]
