# Generated by Django 6.0.5 on 2026-06-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0004_rename_teams_season_id_teamdetailview_team_season_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulationDetailView",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("file_url", models.CharField(max_length=255)),
                ("season_id", models.IntegerField()),
            ],
        ),
    ]
