# Generated by Django 6.0.5 on 2026-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0005_regulationdetailview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nucleodetailview",
            name="logo_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
