# Generated by Django 6.0.5 on 2026-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0006_alter_nucleodetailview_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageConfigView",
            fields=[
                ("_bucket", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                ("welcome_message", models.CharField(max_length=255)),
                ("about_us", models.TextField()),
                ("hero_image_url", models.URLField()),
                ("sponsors", models.JSONField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["_bucket"], name="projections__bucket_960929_idx"
                    )
                ],
            },
        ),
    ]
