# Generated by Django 6.0.5 on 2026-06-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0007_homepageconfigview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageconfigview",
            name="_bucket",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
