# Generated by Django 6.0.5 on 2026-07-07 20:09

from django.db import migrations, models
from workers.projections_updater.service import (
    ProjectionUpdateRequestTypes,
    request_projection_update,
)


def backfill_course_detail_view(apps, schema_editor):
    request_projection_update(
        projection_type=ProjectionUpdateRequestTypes.COURSE, payload={}, key="all"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0008_alter_homepageconfigview__bucket"),
        ("projections_updater", "0004_alter_projectionupdaterequest_projection_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDetailView",
            fields=[
                ("course_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=255)),
                ("nucleo_id", models.UUIDField()),
                ("nucleo_name", models.CharField(max_length=255)),
                ("nucleo_abbreviation", models.CharField(max_length=255)),
                ("nucleo_logo_url", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["course_id"], name="projections_course__12845e_idx"
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_course_detail_view, reverse_code=migrations.RunPython.noop
        ),
    ]
