# Generated by Django 6.0.5 on 2026-07-07 23:43

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
from workers.projections_updater.service import (
    ProjectionUpdateRequestTypes,
    request_projection_update,
)


def backfill_matches_with_courses_and_nucleos_ids(apps, schema_editor):
    request_projection_update(
        projection_type=ProjectionUpdateRequestTypes.MATCH,
        payload={},
        key="all",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0009_coursedetailview"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchdetailview",
            name="courses_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list
            ),
        ),
        migrations.AddField(
            model_name="matchdetailview",
            name="nucleos_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.UUIDField(), blank=True, default=list
            ),
        ),
        migrations.AddIndex(
            model_name="matchdetailview",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["nucleos_ids"], name="projections_nucleos_f0420b_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="matchdetailview",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["courses_ids"], name="projections_courses_734599_gin"
            ),
        ),
        migrations.RunPython(
            backfill_matches_with_courses_and_nucleos_ids,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
