# Generated by Django 6.0.5 on 2026-07-12 15:09

from django.db import migrations, models
from workers.projections_updater.service import (
    ProjectionUpdateRequestTypes,
    request_projection_update,
)


def backfill_tournaments_with_modality_point_unit(apps, schema_editor):
    request_projection_update(
        projection_type=ProjectionUpdateRequestTypes.TOURNAMENT, payload={}, key="all"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0010_matchdetailview_courses_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentdetailview",
            name="modality_point_unit",
            field=models.CharField(default="pt", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(
            backfill_tournaments_with_modality_point_unit,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
