# Generated by Django 6.0.5 on 2026-07-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0011_tournamentdetailview_modality_point_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchdetailview",
            old_name="comment_count",
            new_name="occurrence_count",
        ),
    ]
