# Generated by Django 6.0.5 on 2026-07-13 20:54

from django.db import migrations, models
from workers.projections_updater.service import (
    ProjectionUpdateRequestTypes,
    request_projection_update,
)


def backfill_nucleus_entity_type(apps, schema_editor):
    request_projection_update(ProjectionUpdateRequestTypes.NUCLEO, {}, "all")


class Migration(migrations.Migration):

    dependencies = [
        ("projections", "0012_rename_comment_count_matchdetailview_occurrence_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="nucleodetailview",
            name="entity_type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(
            backfill_nucleus_entity_type, reverse_code=migrations.RunPython.noop
        ),
    ]
