# Generated by Django 6.0.5 on 2026-06-14 18:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=255)),
                ("aggregate_type", models.CharField(db_index=True, max_length=100)),
                ("aggregate_id", models.UUIDField(db_index=True)),
                ("payload", models.JSONField()),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["published", "created_at"],
                        name="events_outb_publish_d14de7_idx",
                    ),
                    models.Index(
                        fields=["event_type", "published"],
                        name="events_outb_event_t_dec085_idx",
                    ),
                    models.Index(
                        fields=["aggregate_type", "aggregate_id"],
                        name="events_outb_aggrega_11f4b9_idx",
                    ),
                ],
            },
        ),
    ]
