FROM python:3.13-slim

WORKDIR /app

COPY src/shared /tmp

COPY src/apis/competition-api-v3/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/apis/competition-api-v3 .

CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]
