"""init

Revision ID: 022586311123
Revises:
Create Date: 2025-12-01 16:54:56.222438

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "022586311123"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournament",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("modality_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("ROUND_ROBIN", "ELIMINATION", "GROUPS", name="tournamenttype"),
            nullable=False,
        ),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="tournaments",
    )
    op.create_index(
        op.f("ix_tournaments_tournament_modality_id"),
        "tournament",
        ["modality_id"],
        unique=False,
        schema="tournaments",
    )
    op.create_table(
        "stage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.tournament.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tournaments",
    )
    op.create_index(
        op.f("ix_tournaments_stage_tournament_id"),
        "stage",
        ["tournament_id"],
        unique=False,
        schema="tournaments",
    )
    op.create_table(
        "journey",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["tournaments.stage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tournaments",
    )
    op.create_index(
        op.f("ix_tournaments_journey_stage_id"),
        "journey",
        ["stage_id"],
        unique=False,
        schema="tournaments",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tournaments_journey_stage_id"),
        table_name="journey",
        schema="tournaments",
    )
    op.drop_table("journey", schema="tournaments")
    op.drop_index(
        op.f("ix_tournaments_stage_tournament_id"),
        table_name="stage",
        schema="tournaments",
    )
    op.drop_table("stage", schema="tournaments")
    op.drop_index(
        op.f("ix_tournaments_tournament_modality_id"),
        table_name="tournament",
        schema="tournaments",
    )
    op.drop_table("tournament", schema="tournaments")
    # ### end Alembic commands ###
