"""init

Revision ID: 824bb29c302e
Revises:
Create Date: 2025-12-06 18:32:34.579287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "824bb29c302e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tournament",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("modality_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("season_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "FINISHED", name="tournamentstatus"),
            nullable=False,
        ),
        sa.Column("rules", sa.JSON(), nullable=True),
        sa.Column("teams", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("finished_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="tournaments",
    )
    op.create_index(
        op.f("ix_tournaments_tournament_modality_id"),
        "tournament",
        ["modality_id"],
        unique=False,
        schema="tournaments",
    )
    op.create_index(
        op.f("ix_tournaments_tournament_season_id"),
        "tournament",
        ["season_id"],
        unique=False,
        schema="tournaments",
    )
    op.create_table(
        "stage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.tournament.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tournaments",
    )
    op.create_index(
        op.f("ix_tournaments_stage_tournament_id"),
        "stage",
        ["tournament_id"],
        unique=False,
        schema="tournaments",
    )
    op.create_table(
        "journey",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stage_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["tournaments.stage.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="tournaments",
    )
    op.create_index(
        op.f("ix_tournaments_journey_stage_id"),
        "journey",
        ["stage_id"],
        unique=False,
        schema="tournaments",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tournaments_journey_stage_id"),
        table_name="journey",
        schema="tournaments",
    )
    op.drop_table("journey", schema="tournaments")
    op.drop_index(
        op.f("ix_tournaments_stage_tournament_id"),
        table_name="stage",
        schema="tournaments",
    )
    op.drop_table("stage", schema="tournaments")
    op.drop_index(
        op.f("ix_tournaments_tournament_season_id"),
        table_name="tournament",
        schema="tournaments",
    )
    op.drop_index(
        op.f("ix_tournaments_tournament_modality_id"),
        table_name="tournament",
        schema="tournaments",
    )
    op.drop_table("tournament", schema="tournaments")
    # ### end Alembic commands ###
