# Generated by Django 6.0.5 on 2026-07-16 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("modalities", "0002_modality_point_unit"),
        ("ranking", "0002_rankingammendment"),
        ("seasons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankingammendment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking_ammendments",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="rankingammendment",
            name="modality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking_ammendments",
                to="modalities.modality",
            ),
        ),
        migrations.AlterField(
            model_name="rankingammendment",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ranking_ammendments",
                to="seasons.season",
            ),
        ),
    ]
