# Generated by Django 6.0.5 on 2026-07-17 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ranking", "0003_alter_rankingammendment_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingammendment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
