# Generated by Django 6.0.5 on 2026-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="course_proof_file_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="athlete",
            name="payment_proof_file_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
