name: CD - Deploy to Production

on:
  push:
    branches:
      - feat/ci-cd

jobs:
  build-and-push:
    name: Build and Push - ${{ matrix.service.name }}
    runs-on: self-hosted
    strategy:
      # Impede que todos os builds parem se um deles falhar
      fail-fast: false
      matrix:
        service:
          - { path: src/apis/competition-api-v2, name: competition-api-v2 }
          # - { path: src/microservices/ranking-service, name: ranking-service }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Service Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.path }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/taca-ua-${{ matrix.service.name }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/taca-ua-${{ matrix.service.name }}:stable
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  deploy:
    name: Deploy to Production
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout code (to get docker-compose file)
        uses: actions/checkout@v4

      - name: Local Docker Compose Deploy
        run: |
          cd $GITHUB_WORKSPACE
          
          # 1. Puxar as imagens atualizadas do Docker Hub
          docker compose pull
          
          # 2. Subir os serviços
          # O --remove-orphans limpa serviços antigos que foram removidos do yaml
          docker compose up -d --remove-orphans
          
          # 3. Limpeza de disco: remove imagens 'dangling' que ficaram para trás
          docker image prune -f