FROM node:26-alpine
WORKDIR /app
COPY src/frontend/public-website/package*.json ./
RUN npm install
COPY src/frontend/public-website .
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
